## Sparse Matrix Representation

### Tools

In [ ]:
def is_sparse(matrix):
    if matrix is None or not any(matrix):
        return True
    if isinstance(matrix, list):
        z = sum(1 for i in matrix if i == 0 or (isinstance(i, list) and 0 in i))
        nz = sum(1 for i in matrix if i != 0 and (not isinstance(i, list) or 0 not in i))
        if z > nz:
            if all(isinstance(row, (int, float))for row in matrix):
                return True
            else:
                if all(isinstance(row, list) for row in matrix):
                    num_cols = len(matrix[0])
                    if all(len(row) == num_cols for row in matrix):
                        return True
    return False

def Scan(T, name=''):
    i = T.__name__
    while True:
        exp = input(f'Enter {i} {name}: ')
        if not exp.strip():
            return None
        try:
            l = eval(exp)
            if is_sparse(l):
                return SparseMatrix(l)
            print(f"{i} is required.")
        except Exception as e:
            print("Error:", e)

### Questions

1. Implement a class to represent a sparse matrix using coordinate list representation

  (a)Initialize a sparse matrix with a given number of rows and columns.

  (b)Insert elements into the sparse matrix.

  (c )Display the sparse matrix.



In [ ]:
import numpy as np

class SparseMatrix:
    def __init__(self, rows, cols, matrix = None):
        self.rows, self.cols = rows, cols
        if matrix is None or not any(matrix):
            self.data = [(rows, cols, 0)]
        else:
            self.data = [(i, j, matrix[i-1][j-1]) for i in range(1, self.rows+1) for j in range(1, self.cols+1) if matrix[i-1][j-1] != 0]
            self.data = [(rows, cols, len(self.data))] + self.data

    def __str__(self):
        m = [max(len(str(x[i])) for x in self.data) for i in range(3)]
        rows = ['[{:>{}}  {:>{}}  {:>{}}]'.format(i[0], m[0], i[1], m[1], i[2], m[2]) for i in self.data]
        s = '[' + '\n '.join(rows) + ']'
        return s

    def __iter__(self):
        return iter(self.data)

In [ ]:
rows = int(input("Rows = "))
cols = int(input("Columns = "))

print(f"Enter values for matrix {'A'}:")
matrix = [[float(input(f"{'A'}[{i}][{j}]: ")) for j in range(1, cols+1)] for i in range(1, rows+1)]
matrix = [[int(x) if x.is_integer() else x for x in i] for i in matrix]

A = SparseMatrix(rows, cols, matrix)
print()
print(A)

Rows = 5
Columns = 6
Enter values for matrix A:
A[1][1]: 0
A[1][2]: 0
A[1][3]: 0
A[1][4]: 6
A[1][5]: 0
A[1][6]: 0
A[2][1]: 0
A[2][2]: 7
A[2][3]: 0
A[2][4]: 0
A[2][5]: 0
A[2][6]: 0
A[3][1]: 0
A[3][2]: 2
A[3][3]: 0
A[3][4]: 5
A[3][5]: 0
A[3][6]: 0
A[4][1]: 0
A[4][2]: 0
A[4][3]: 0
A[4][4]: 0
A[4][5]: 0
A[4][6]: 0
A[5][1]: 4
A[5][2]: 0
A[5][3]: 0
A[5][4]: 0
A[5][5]: 0
A[5][6]: 0

[[5  6  5]
 [1  4  6]
 [2  2  7]
 [3  2  2]
 [3  4  5]
 [5  1  4]]



In [ ]:
rows = int(input("Rows = "))
cols = int(input("Columns = "))
print("Enter the matrix elements row-wise:")

matrix = [list(map(int, input().split())) for i in range(rows)]
A = SparseMatrix(rows, cols, matrix)
print()
print(A)

Rows = 5
Columns = 6
Enter the matrix elements row-wise:
0 0 0 6 0 0
0 7 0 0 0 0
0 2 0 5 0 0
0 0 0 0 0 0
4 0 0 0 0 0

[[5  6  5]
 [1  4  6]
 [2  2  7]
 [3  2  2]
 [3  4  5]
 [5  1  4]]


2. Write a function to add two sparse matrices and return the resulting sparse matrix. Ensure that the matrices being added are compatible for addition.


In [ ]:
class SparseMatrix:
    def __init__(self, matrix = None, data = None):
        if data is None:
            if matrix is None or not any(matrix):
                self.data = [(0, 0, 0)]
            else:
                try:
                    rows = len(matrix)
                    cols = len(matrix[0])
                    self.data = [(i, j, matrix[i - 1][j - 1]) for i in range(1, rows + 1) for j in range(1, cols + 1)
                                if matrix[i - 1][j - 1] != 0]
                except:
                    rows = 1
                    cols = len(matrix)
                    self.data = [(1, i, matrix[i - 1]) for i in range(1, cols + 1) if matrix[i - 1] != 0]

                self.data = [(rows, cols, len(self.data))] + self.data
        else:
            self.data = data

    def __str__(self):
        m = [max(len(str(x[i])) for x in self.data) for i in range(3)]
        rows = ['[{:>{}}  {:>{}}  {:>{}}]'.format(i[0], m[0], i[1], m[1], i[2], m[2]) for i in self.data]
        s = '[' + '\n '.join(rows) + ']'
        return s

    def __iter__(self):
        return iter(self.data)

    def add(self, other):
        if self.data[0][:2] != other.data[0][:2]:
            raise ValueError("Matrices must have the same dimensions for addition.")

        result = (self.data).copy()
        for i in range(1, len(other.data)):
            for j in range(1, len(result)):
                if other.data[i][:2] == result[j][:2]:
                    result[j] = result[j][:2] + (result[j][2]+other.data[i][2],)
                    break
            else:
                result.append(other.data[i])
        result[0] = result[0][:-1]+(len(result)-1,)
        result = [result[0]] + sorted(result[1:])
        return SparseMatrix(data = result)

In [ ]:
A = Scan(SparseMatrix, 'A')
print("Sparse Matrix A:")
print(A)
print()

B = Scan(SparseMatrix, 'B')
print("Sparse Matrix B:")
print(B)
print()

try:
    result = A.add(B)
    print("Sum of 2 matrices:")
    print(result)
except ValueError as e:
    print("Error during addition:", e)


Enter SparseMatrix A: [[0,0,0],[1,2,0]]
Sparse Matrix A:
[[2  3  2]
 [2  1  1]
 [2  2  2]]

Enter SparseMatrix B: [[0,3,0],[9,0,0]]
Sparse Matrix B:
[[2  3  2]
 [1  2  3]
 [2  1  9]]

Sum of 2 matrices:
[[2  3   3]
 [1  2   3]
 [2  1  10]
 [2  2   2]]



3. Implement a function to find and display the transpose of a given sparse matrix.


In [ ]:
class SparseMatrix:
    def __init__(self, matrix=None, data = None):
        if data is None:
            if matrix is None or not any(matrix):
                self.data = [(0, 0, 0)]
                self.rows = self.cols = 0
            else:
                try:
                    self.rows = len(matrix)
                    self.cols = len(matrix[0])
                    self.data = [(i, j, matrix[i - 1][j - 1]) for i in range(1, self.rows + 1) for j in range(1, self.cols + 1)
                                if matrix[i - 1][j - 1] != 0]
                except:
                    self.rows = 1
                    self.cols = len(matrix)
                    self.data = [(1, i, matrix[i - 1]) for i in range(1, self.cols + 1) if matrix[i - 1] != 0]

                self.data = [(self.rows, self.cols, len(self.data))] + self.data
        else:
            self.data = data

    def __str__(self):
        m = [max(len(str(x[i])) for x in self.data) for i in range(3)]
        rows = ['[{:>{}}  {:>{}}  {:>{}}]'.format(i[0], m[0], i[1], m[1], i[2], m[2]) for i in self.data]
        s = '[' + '\n '.join(rows) + ']'
        return s

    def __iter__(self):
        return iter(self.data)

    def transpose(self):
        transposed_data = [(col, row, value) for row, col, value in self.data]
        transposed_data = [transposed_data[0]] + sorted(transposed_data[1:])
        return SparseMatrix(data = transposed_data)


In [ ]:
A = Scan(SparseMatrix, 'A')
print("Sparse Matrix A:")
print(A)
print()
B = A.transpose()
print("Transpose of Matrix A:")
print(B)

Enter SparseMatrix A: [[1,23],[0,0],[0,1]]
Sparse Matrix A:
[[3  2   3]
 [1  1   1]
 [1  2  23]
 [3  2   1]]

Transpose of Matrix A:
[[2  3   3]
 [1  1   1]
 [2  1  23]
 [2  3   1]]



4. Write a function to find the inverse of a sparse matrix if it is invertible

In [ ]:
class SparseMatrix:
    def __init__(self, matrix=None, data = None):
        if data is None:
            if matrix is None or not any(matrix):
                self.data = [(0, 0, 0)]
                self.rows = self.cols = 0
            else:
                try:
                    self.rows = len(matrix)
                    self.cols = len(matrix[0])
                    self.data = [(i, j, matrix[i - 1][j - 1]) for i in range(1, self.rows + 1) for j in range(1, self.cols + 1)
                                if matrix[i - 1][j - 1] != 0]
                except:
                    self.rows = 1
                    self.cols = len(matrix)
                    self.data = [(1, i, matrix[i - 1]) for i in range(1, self.cols + 1) if matrix[i - 1] != 0]

                self.data = [(self.rows, self.cols, len(self.data))] + self.data
        else:
            self.data = data

    def __str__(self):
        m = [max(len(str(x[i])) for x in self.data) for i in range(3)]
        rows = ['[{:>{}}  {:>{}}  {:>{}}]'.format(i[0], m[0], i[1], m[1], i[2], m[2]) for i in self.data]
        s = '[' + '\n '.join(rows) + ']'
        return s

    def __iter__(self):
        return iter(self.data)

    def inv(self):
        A = [[0 for i in range(self.data[0][1])]for i in range(self.data[0][0])]
        for i in self.data[1:]:
            A[i[0]-1][i[1]-1] = i[2]
        n = len(A)
        identity = [[1 if i == j else 0 for j in range(n)] for i in range(n)]
        for i in range(n):
            A[i].extend(identity[i])

        for i in range(n):
            max_index = i
            for j in range(i + 1, n):
                if abs(A[j][i]) > abs(A[max_index][i]):
                    max_index = j
            A[i], A[max_index] = A[max_index], A[i]
            pivot = A[i][i]
            if pivot == 0:
                # raise ValueError("Matrix is singular.")
                print('warning: matrix singular to machine precision')

            for j in range(i, 2 * n):
                A[i][j] /= pivot

            for j in range(n):
                if i != j:
                    factor = A[j][i]
                    for k in range(i, 2 * n):
                        A[j][k] -= factor * A[i][k]

        inverse = [row[n:] for row in A]

        return inverse


In [ ]:
A = Scan(SparseMatrix, 'A')
print("Sparse Matrix A:")
print(A)
print()
B = A.inv()

print("Inverse A:")

if is_sparse(B):
    B = SparseMatrix(B)
    print(B)
else:
    m = [max(len(str(x[i])) for x in B) for i in range(3)]
    rows = ['[{:>{}}  {:>{}}  {:>{}}]'.format(i[0], m[0], i[1], m[1], i[2], m[2]) for i in B]
    s = '[' + '\n '.join(rows) + ']'
    print(s)

Enter SparseMatrix A: [[0,1,0],[1,1,0],[0,0,2]]
Sparse Matrix A:
[[3  3  4]
 [1  2  1]
 [2  1  1]
 [2  2  1]
 [3  3  2]]

Inverse A:
[[3  3     4]
 [1  1  -1.0]
 [1  2   1.0]
 [2  1   1.0]
 [3  3   0.5]]


## Block Matrix Representation

### Tools

In [ ]:
def is_matrix(obj):
    if not isinstance(obj, list) or not any(obj):
        return False

    num_cols = None

    for row in obj:
        if not isinstance(row, list):
            return False
        if num_cols is None:
            num_cols = len(row)
        elif len(row) != num_cols:
            return False
        for element in row:
            if not isinstance(element, (int, float)):
                return False

    return True

def convert(matrix):
    if isinstance(matrix, list) and len(matrix) > 0 and isinstance(matrix[0], list):
        return matrix
    else:
        return [matrix]

def Scan(name=''):
    while True:
        exp = input(name)
        try:
            l = eval(exp)
            if is_matrix(convert(l)):
                return l
            print(f"matrix is required.")
        except Exception as e:
            print("Error:", e)



### Questions

5. Implement a class to represent a block matrix. The matrix should be divided into square blocks.

  (a)Initialize a block matrix with a given size and block size.

  (b)Insert elements into the block matrix.

  (c)Display the block matrix.



In [ ]:
import numpy as np

class BlockMatrix:
    def __init__(self,matrix):
      matrix = np.vstack([np.hstack(x) for x in l])
      self.data = [list(x) for x in matrix]

    def __str__(self):
        max_width = max(len(str(item)) for row in self.data for item in row)
        matrix_str = ''
        for row in self.data:
            matrix_str += ' '.join(str(item).rjust(max_width) for item in row) + '\n'
        return matrix_str

    def __iter__(self):
        return iter(self.data)

l = []
var = {}
v = input("Matrix structure (having blocks as variables) = ").replace(' ','')

if v.count('[') == 1 and v.count(']') == 1:
    v = f'[{v}]'

w = v.replace(']','').replace('[','')


k = [x + f'={Scan(f"{x} = ")}' for x in w.split(',') if x.isidentifier()]+ ['l = ' + v]
for i in k:
  try:
      exec(i, {}, var)
  except Exception as e:
      print("Error:", e)

for key, value in var.items():
    globals()[key] = value

try :
  l = BlockMatrix(l)
  print("\nMatrix: ")
  print(l)
except :
  print("\nAll block matrix should be of same dimensions")

Matrix structure (having blocks as variables) = [[a,b],[c,d]]
a = [[1,2],[3,4]]
b = [[5,6],[7,8]]
c = [[9,10],[11,12]]
d = [[13,14],[15,16]]

Matrix: 
 1  2  5  6
 3  4  7  8
 9 10 13 14
11 12 15 16



6.  Conformal Decomposition

  Write a function to perform conformal decomposition on a given matrix. Decompose the matrix into a sum of matrices representing its diagonal and off-diagonal blocks.

  Example:

  Input Matrix:
  \begin{matrix}
  1 & 2 & 3 \\
  4 & 5 & 6 \\
  7 & 8 & 9 \\
  \end{matrix}

  Diagonal Blocks:

  \begin{matrix}
  1 & 0 & 0 \\
  0 & 5 & 0 \\
  0 & 0 & 9 \\
  \end{matrix}

  Off-diagonal Blocks:

  \begin{matrix}
  0 & 2 & 3 \\
  4 & 0 & 6 \\
  7 & 8 & 0 \\
  \end{matrix}


In [ ]:
def conformal_decomposition(matrix):
    rows = len(matrix)
    cols = len(matrix[0])
    n = min((rows,cols))

    diag = [[matrix[i][j] if i == j else 0 for j in range(n)] for i in range(n)]
    off_diag = [[0 if i == j else matrix[i][j] for j in range(n)] for i in range(n)]

    return diag, off_diag

A = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]
print("Input Matrix:")
for row in A:
    print(row)


diag, off_diag = conformal_decomposition(A)

print("\nDiagonal Blocks:")
for row in diag:
    print(row)

print("\nOff-diagonal Blocks:")
for row in off_diag:
    print(row)


Input Matrix:
[1, 2, 3]
[4, 5, 6]
[7, 8, 9]

Diagonal Blocks:
[1, 0, 0]
[0, 5, 0]
[0, 0, 9]

Off-diagonal Blocks:
[0, 2, 3]
[4, 0, 6]
[7, 8, 0]
